---
# Define 'Secret' to store db-credentials 
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  labels:
    app: mysql
    tier: database
type: Opaque
data:
  username: dXNlcg== # base64 encoded 'user'
  password: ZGV2ZWxvcA== # base64 encoded 'develop'
