---
# Define 'Secret' to store 'root' user Credentials
apiVersion: v1
kind: Secret
metadata:
  name: db-root-credentials
  labels:
    app: mysql
    tier: database
type: Opaque
data:
  password: bWFnaWM= # base64 encoded 'magic'
