---
services:
  postgres:
    image: postgres:16
    container_name: headless-postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - headless_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  headless_postgres_data:
