kubectl -n longhorn-system patch deployment longhorn-manager --patch '{
  "spec": {
    "template": {
      "spec": {
        "containers": [
          {
            "name": "longhorn-manager",
            "resources": {
              "limits": {
                "cpu": "500m",
                "memory": "512Mi"
              },
              "requests": {
                "cpu": "100m",
                "memory": "256Mi"
              }
            }
          }
        ]
      }
    }
  }
}'
