# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: service-name
  namespace: default
spec:
  selector:
    app: service-name
  type: ClusterIP
  ports:
    - name: service-name
      protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30001
---

