name: On Push Workflow
on:
  push:
    branches: ["main"]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4

      - name: Run echo for logs
        run: |
          echo "hehe logs 1"
          echo "hihi logs 2"
