apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  # namespace: three-tier-app
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  hostPath: # For development/testing. Use proper storage class in production
    path: "/mnt/data/postgres"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: three-tier-app
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 10Gi
